### ISSUE TITLE
Fix FreeRTOS runtime logging.

### ISSUE THREAD

**Issue by Redperij** [vas-dav/SHOH-Innovation-Project#55]
- Seems that it is unable to handle 32-bit timer overflows.

Possible solution: Hook it to the custom timer, which handles overflows?

**Comment by vas-dav** [comment]
Check first https://www.nxp.com/docs/en/training-reference-material/AMF-SOL-ADVANCED-DEBUG-MCUXPRESSO-IDE-PRESENTATION.pdf PAGE 53
